name: "environments"

on:
  pull_request:
    branches:
      - main
#    paths:
#      - "environments/**"
  push:
    branches:
      - main
#    paths:
#      - "environments/**"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: calculate diff
        run: git diff-tree --no-commit-id --name-only -r ${{ github.sha }}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"