name: "environments"

on:
  pull_request:
#    branches:
#      - main
#    paths:
#      - "environments/**"
  push:
#    branches:
#      - main
#    paths:
#      - "environments/**"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: calculate diff
        id: calculate
        env:
          AFTER: "${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.event.after }}"
          BEFORE: "${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}"
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "before: $BEFORE"
          echo "after: $AFTER"
          echo "::set-output name=DIFF::$(git diff-tree --no-commit-id --name-only -r $BEFORE $AFTER)"

      - name: print diff
        run: |
          echo "diff: ${{ steps.calculate.outputs.DIFF }}"

